name: JS Actions

on: 
  push:
  pull_request:
    types: [labeled]

jobs:

  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: Daniel
          second-greeting: Luis
          third-greeting: Rita
        
  joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: ha-ha
        uses: ./.github/actions/joke-action        
